### ISSUE TITLE
Issue with WP YouTube Lyte thumbnail image generation

### ISSUE THREAD

**Issue by jake-101** [Mecanik/cloudflare-image-resizing#13]
WP Youtube Lyte has a thumbnail image caching feature. Cloudflare image resizing is trying to rearrange the URL in the WP YouTube Lyte thumbnail cache:

An example URL: https://website.com/wp-content/plugins/wp-youtube-lyte/lyteCache.php?origThumbUrl=https%3A%2F%2Ftilta.com%2Fcdn-cgi%2Fimage%2Fquality%3D65%2Cformat%3Dauto%2Conerror%3Dredirect%2Cmetadata%3Dnone%2Fvi%2FybDY8eRnNEA%2Fmaxresdefault.jpg

It should be showing ytimg.com instead of my website url and returns an error. Deactivating the plugin doesn't seem to resolve the issue. Any ideas on how to fix this? thanks

**Comment by Mecanik** [comment]
> WP Youtube Lyte has a thumbnail image caching feature. Cloudflare image resizing is trying to rearrange the URL in the WP YouTube Lyte thumbnail cache:
> 
> An example URL: https://website.com/wp-content/plugins/wp-youtube-lyte/lyteCache.php?origThumbUrl=https%3A%2F%2Ftilta.com%2Fcdn-cgi%2Fimage%2Fquality%3D65%2Cformat%3Dauto%2Conerror%3Dredirect%2Cmetadata%3Dnone%2Fvi%2FybDY8eRnNEA%2Fmaxresdefault.jpg
> 
> It should be showing ytimg.com instead of my website url and returns an error. Deactivating the plugin doesn't seem to resolve the issue. Any ideas on how to fix this? thanks

My plugin should will not attempt to re-write such URL's at all, so I believe your problem is coming from somewhere else. Your statement also confirms this: "_Deactivating the plugin doesn't seem to resolve the issue._".

I would honestly ditch that plugin because in reality it does nothing that you cannot do already by yourself.

`<iframe loading="lazy"`

_This HTML feature allows lazy loading YouTube iframe embeds only when the user scrolls over them, without any extra JavaScript (the YouTube video is of course automatically loaded via JavaScript in the iframe however)._

[https://web.dev/iframe-lazy-loading/](https://web.dev/iframe-lazy-loading/)

**Comment by jake-101** [comment]
thanks for the reply
