### ISSUE TITLE
Saves http instead of https

### ISSUE THREAD

**Issue by mattwmc** [Mecanik/cloudflare-image-resizing#26]
The site url is being saved as http instead of https on the options-general.php?page=cf-image-resizing-settings page.

This breaks the images sites using https.

I had to manually change my site url in config.php to https and everything works.

![cf-image-1](https://user-images.githubusercontent.com/36112980/203174806-e013bb6d-c778-4c85-84e3-eaa01dac46f5.jpg)

**Comment by mdfathi99** [comment]
Hi there check the Image URL parameter. 

`https://example.com/http://example.com/cdn-cgi/image/width=1080,height=1080,fit=crop,quality=80,format=auto,onerror=redirect,metadata=none/wp-content/uploads/2022/04/11-1-optimized.jpg`

so this parameter will not work. Because the written URL will add after the main URL. So, instead add a dot `.` in the Site URL field. And boom it will work.

**Comment by Mecanik** [comment]
This is because of how your WordPress was installed and configured, has nothing to do with the plugin itself.
