### ISSUE TITLE
Plugin wont activate/install

### ISSUE THREAD

**Issue by hairybridget** [Mecanik/cloudflare-image-resizing#27]
Strange issue. I've successfully installed your plugin on other WP sites in the past, but downloading your zip and uploading it via WP dashboard > Plugins results in an error:

> Installing plugin from uploaded file: cloudflare-image-resizing-main.zip
> Unpacking the package…
> 
> Installing the plugin…
> 
> The package could not be installed. No valid plugins were found.
> 
> Plugin installation failed.

Any idea what I may be doing wrong?

**Comment by mdfathi99** [comment]
Hi, go to Plugins>Add New> Then search "CF Image Resizing"
And then active the plugin. After activation if you don't find the URL setting page.  then add this your URL and `/wp-admin/options-general.php?page=cf-image-resizing-settings` And in the URL field add `.` only and click save. Don't use your URL because it will not work.

**Comment by Mecanik** [comment]
Something might have changed in the latest WordPress version, I will check when I have time and update it.

**Comment by Mecanik** [comment]
Hello, I am closing this issue since I have finally finished the Cloudflare Worker alternative. It's much more advanced and does not have this issue.

Please read my article on how to use and get the code: https://mecanik.dev/en/posts/cloudflare-image-resizing-for-wordpress/
