### ISSUE TITLE
High Load with Plugin

### ISSUE THREAD

**Issue by mdotk** [Mecanik/cloudflare-image-resizing#36]
Enabling this plugin causes lots of php-fpm processes and my load goes way too high.

Have you encountered this before?

**Comment by Mecanik** [comment]
No, and it's unrelated. The plugin does not do anything special for your PHP-FPM to go up. Most likely you are using a bad setup, cheap hosting, or something similar. Also, PHP-FPM requires extensive knowledge and configuration to work properly. 

My suggestion is to use LSAPI, the fastest PHP processor ever made. But not many offer it, because it's expensive. If interested, you can checkout my own WP Hosting (link inside plugin).

**Comment by mdotk** [comment]
Fixed. I don't know what the issue was, but it is resolved now.
