### ISSUE TITLE
The <region> specified is invalid.

### ISSUE THREAD

**Issue by Dyras** [Mecanik/cloudflare-image-resizing#40]
Hello! I deactivated the plugin on localhost as it doesn't work there, and I'm asked to write why I'm deactivating it.

When I try to do so, however, it gives me this message:
![image](https://github.com/Mecanik/cloudflare-image-resizing/assets/12563436/308028db-168e-4f90-9a43-d04ab008c9db)

"Skip and deactivate" works flawlessly, however.

Setup:
WordPress 6.3.2 using Sage 9 with MariaDB.
PHP 8.1.

**Comment by Mecanik** [comment]
Hello,

Thank you for reporting this issue, I am very surprised this is happening. The way I create this bit is that each feedback is stored in a specific region and for some reason the region was not set for you.

Can you please check the latest version? (1.5.4) If this behaves the same way, can you please do the following for me:

1. Go to https://reqbin.com/
2. Enter URL: https://api.mecanik.dev/v1/developer/af87c346-67e8-4c94-a4d2-c5a5db65b4c7/geo-info
3. Enter Authorization Token: lu-3VkkHTqTOnQ8JDRuadMAJErJQvBSQXaZL04igSTs

Execute a GET request and show me the response please.

**Comment by Mecanik** [comment]
Thank you for this. I cannot believe my eyes... when the code cannot determine your "default" region, it should return one. Instead of returning the correct region, it returned literally "default" (`"recommended-storage-region": "default"`)... I have fixed this now and it should work accordingly.

Still curious why based on your GEO info the region cannot be determined.
